# Generated by Django 4.2.6 on 2023-10-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('$', 'Affordable'), ('$$', 'Expensive'), ('$$$', 'Very Expensive')], default='$', max_length=3),
        ),
    ]
