# Generated by Django 4.2.6 on 2023-10-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
